samples: "config/samples1.tsv" # .tsv file containing sample names and locations
regions: "config/regions.tsv" # .tsv file containing bed files with regions of interest

tissue: ["CACO.2", "MCF7", "PC.3"] # tissues for generating plots
refSample: "NPH001" # reference sample for rank correlation comparison
minRL: 120 # minimum read length for calculating WPS
maxRL: 180 # maximum read length for calculating WPS
bpProtection: 120 